default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 784512mbl
  host: localhost
  port: 5432


development:
  <<: *default
  database: e_commerce_development

test:
  <<: *default
  database: e_commerce_test
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

production:
  primary: &primary_production
    <<: *default
    database: e_commerce_production
    username: e_commerce
    password: <%= ENV["E_COMMERCE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: e_commerce_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: e_commerce_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: e_commerce_production_cable
    migrations_paths: db/cable_migrate
